[package]
name = "day19"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.*", features = ["derive"] }
regex = "*"
# rand = "*"
# nom = "*"


[[bin]]
name = "day19"
path = "day19.rs"
