[package]
name = "day25"
version = "0.1.0"
edition = "2021"

[dependencies]
aoc = { path = "../../aoc" }
assembunny = { path = "../assembunny/" }
num-traits = "*"

[[bin]]
name = "day25"
path = "day25.rs"
