[package]
name = "day16"
version = "0.1.0"
edition = "2021"

[features]
anim = []

[dependencies]
aoc = { path = "../../aoc" }
aoc24 = { path = "../aoc24" }
image = "*"

[[bin]]
name = "day16"
path = "day16.rs"