[package]
name = "day16"
version = "0.1.0"
edition = "2021"

[features]
anim = []

[dependencies]
aoc = { path = "../../aoc" }
image = "*"
rustc-hash = "2.1.0"

[[bin]]
name = "day16"
path = "day16.rs"
