# http://adventofcode.com/2017

[workspace]
members = [
    "day1",
    "day2",
    "day5",
    "day8",
    "day10",
    "day11",
    "day13",
    "day14",
    "day15",
    "day16",
    "day17",
    "day18",
    "day23",
]

resolver = "2"
