# https://adventofcode.com/2019

[workspace]
members = [
    "day1",
    "day2",
    "day3",
    "day4",
    "day5",
    "day6",
    "day7",
    "day8",
    "day10",
    "day12",
    "day14",
    "day16",
    "day18",
    "day20",
    "day22",
    "day24",
    "intcode-rs",
]

resolver = "2"
