# https://adventofcode.com/2018

[workspace]
members = [
    "day1",
    "day2",
    "day3",
    "day4",
    "day6",
    "day8",
    "day10",
    "day12",
    "day16",
    "day18",
    "day22",
    "day24",
]

resolver = "2"
