[package]
name = "day13_nom"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.*", features = ["derive"] }
nom = "*"
# regex = "*"
# rand = "*"

[[bin]]
name = "day13_nom"
path = "day13.rs"
