[package]
name = "day10"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.1.0", features = ["derive"] }
phf = { version = "0.11.1", features = ["macros"], default-features = false }

[[bin]]
name = "day10"
path = "day10.rs"
