[package]
name = "day15"
version = "0.1.0"
edition = "2021"

[features]
anim = ["image"]

[dependencies]
aoc = { path = "../../aoc" }
rustc-hash = "*"
image = { version = "*", optional = true }

[[bin]]
name = "day15"
path = "day15.rs"
