[package]
name = "day22"
version = "0.1.0"
edition = "2021"

[dependencies]
aoc = { path = "../../aoc" }
strum = { version = "*", features = ["strum_macros", "derive"] }
strum_macros = "*"

[[bin]]
name = "day22"
path = "day22.rs"
