[package]
name = "day10"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.*", features = ["derive"] }
aoc2018 = { path = "../aoc2018" }

[[bin]]
name = "day10"
path = "day10.rs"
