[package]
name = "day13"
version = "0.1.0"
edition = "2021"

[dependencies]
structopt = "0.3"
phf = { version = "0.11.1", features = ["macros"], default-features = false }

[[bin]]
name = "day13"
path = "day13.rs"
