[package]
name = "day8"
version = "0.1.0"
edition = "2021"

[dependencies]
aoc = { path = "../../aoc" }
pest = { version = "2", default-features = false }
pest_derive = { version = "2", default-features = true }
rustc-hash = "2.1.0"

[[bin]]
name = "day8"
path = "day8.rs"
