[package]
name = "day8"
version = "0.1.0"
edition = "2021"

[dependencies]
aoc = { path = "../../aoc" }
lazy_static = "1.4.0"
pest = "2.7.5"
pest_derive = "2.7.5"

[[bin]]
name = "day8"
path = "day8.rs"
