[package]
name = "day18"
version = "0.1.0"
edition = "2021"

[features]
ascii = []
anim = ["image"]

[dependencies]
aoc = { path = "../../aoc" }
image = { version = "*", optional = true }

[[bin]]
name = "day18"
path = "day18.rs"
