FROM fedora

RUN dnf upgrade -y && \
    dnf install -y vim curl wget sudo sqlite3 vim && \
    dnf group install -y development-tools c-development && \
    dnf install -y cmake gdb clang llvm z3-devel

# Python
RUN dnf install -y python3-pip python3-devel python3-numpy python3-tabulate python3-click python3-curtsies python3-shapely python3-sympy python3-networkx python3-z3
RUN python3 -mvenv /venv/python --system-site-packages

# Rust
RUN dnf install -y cargo cargo-fmt cargo-clippy

# Golang
RUN dnf install -y golang

# Lua
RUN dnf install -y lua

# Ruby
RUN dnf install -y ruby

# C#
RUN dnf install -y mono-devel

# Swift
RUN dnf install -y swift-lang

# JavaScript
RUN dnf install -y nodejs

# Java
RUN dnf install -y java-latest-openjdk-devel || true

# User environment
ENV Z3_SYS_Z3_HEADER=/usr/include/z3/z3.h

ARG HOST_U=1027
ARG HOST_G=100
ARG HOST_UN=user
RUN useradd --create-home --no-user-group -g $HOST_G -u $HOST_U $HOST_UN
RUN echo "$HOST_UN ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers
RUN echo 'export SHELL=/bin/bash' >> /etc/bash.bashrc
RUN echo 'alias ll="ls -l --color"' >> /etc/bash.bashrc

RUN echo '[ -f /venv/python/bin/activate ] && source /venv/python/bin/activate' >> /etc/bash.bashrc
