FROM fedora

RUN dnf upgrade -y && \
    dnf install -y bash vim curl wget sudo sqlite3 && \
    dnf install -y python3-pip python3-numpy python3-tabulate python3-click python3-curtsies && \
    dnf group install -y development-tools c-development && \
    dnf install -y clang z3-devel sqlite-devel

# Python
RUN dnf install -y python3-shapely python3-sympy python3-networkx python3-z3
RUN python3 -mvenv /venv/python --system-site-packages

# Rust
RUN dnf install -y cargo cargo-fmt cargo-clippy rust-src

# Golang
RUN dnf install -y golang

# Lua
RUN dnf install -y lua

# Ruby
RUN dnf install -y ruby

# C#
RUN dnf install -y mono-devel

# Swift
RUN dnf install -y swift-lang

# JavaScript
RUN dnf install -y nodejs

# Java
RUN dnf install -y java-latest-openjdk-devel || true

# Python and virtualenvs
ENV PATH="/root/.local/bin:$PATH"
RUN curl -LsSf https://astral.sh/uv/install.sh | sh && \
    uv python install 3.11 3.12 3.13 3.14

# User environment
ENV Z3_SYS_Z3_HEADER=/usr/include/z3/z3.h

WORKDIR /aoc

RUN . /etc/os-release && \
    echo "export AOC_TARGET_DIR=target/${ID}-${VERSION_ID}" >> /etc/bashrc && \
    echo "export CARGO_TARGET_DIR=target/${ID}-${VERSION_ID}/$(rustc --version | cut -f2 -d' ')-$(rustc --print host-tuple)" >> /etc/bashrc

CMD ["/bin/bash"]
