FROM debian:sid

RUN apt-get update && \
    apt-get upgrade -y && \
    apt-get install -y vim curl wget sudo sqlite3 vim && \
    apt-get install -y build-essential cmake gdb python3-full python3-numpy python3-tabulate python3-click python3-curtsies python3-shapely python3-sympy python3-networkx python3-z3 && \
    apt-get install -y clang llvm && \
    apt-get install -y z3

# Rust
RUN apt-get install -y cargo rust-all

# Golang
RUN apt-get install -y -qq golang

# Lua
RUN apt-get install -y -qq lua5.4

# Ruby
RUN apt-get install -y -qq ruby

# C#
RUN apt-get install -y -qq mono-mcs

# Swift
RUN env DEBIAN_FRONTEND=noninteractive apt-get install -y -qq swiftlang

# JavaScript
RUN apt-get install -y -qq nodejs

# Java
RUN apt-get install -y -qq default-jdk

# User environment
ARG HOST_U=1027
ARG HOST_G=100
ARG HOST_UN=user
RUN useradd --create-home --no-user-group -g $HOST_G -u $HOST_U $HOST_UN
RUN echo "$HOST_UN ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers
RUN echo 'export SHELL=/bin/bash' >> /etc/bash.bashrc
RUN echo 'alias ll="ls -l --color"' >> /etc/bash.bashrc

RUN echo '[ -f /venv/python/bin/activate ] && source /venv/python/bin/activate' >> /etc/bash.bashrc
