FROM rust:alpine

RUN apk update && \
    apk add --no-cache bash vim curl wget sudo sqlite && \
    apk add --no-cache py3-click py3-tabulate py3-numpy && \
    apk add --no-cache clang clang-dev sqlite-dev z3-dev

ENV RUSTFLAGS='-C target-feature=-crt-static'

ENV PATH="/root/.local/bin:$PATH"
RUN curl -LsSf https://astral.sh/uv/install.sh | sh && \
    uv python install 3.11 3.14

WORKDIR /aoc

RUN . /etc/os-release && \
    echo "export AOC_TARGET_DIR=target/${ID}-${VERSION_ID}" >> /etc/bash/bashrc && \
    echo "export CARGO_TARGET_DIR=target/${ID}-${VERSION_ID}/$(rustc --version | cut -f2 -d' ')-$(rustc --print host-tuple)" >> /etc/bash/bashrc

CMD ["/bin/bash"]
