[package]
name = "day21"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.*", features = ["derive"] }
# regex = "*"
# rand = "*"
fraction = "*"
num = "*"

[[bin]]
name = "day21"
path = "day21.rs"
