[package]
name = "day11"
version = "0.1.0"
edition = "2021"

[dependencies]
aoc = { path = "../../aoc" }
intcode = { path = "../intcode-rs" }
rustc-hash = "2.1.0"

[[bin]]
name = "day11"
path = "day11.rs"
