[package]
name = "day24"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[dependencies]
aoc = { path = "../../aoc" }
fraction = "0.14.0"
z3 = "0.12.1"

[[bin]]
name = "day24"
path = "day24.rs"
