[package]
name = "day23"
version = "0.1.0"
edition = "2021"

[dependencies]
aoc = { path = "../../aoc" }
rustworkx-core = "*"
petgraph = "*"
rustc-hash = "2.1.0"

[[bin]]
name = "day23"
path = "day23.rs"
