[package]
name = "day8"
version = "0.1.0"
edition = "2021"

[dependencies]
aoc = { path = "../aoc/" }
regex = "^1.5.4"
phf = { version = "0.11.1", features = ["macros"], default-features = false }

[[bin]]
name = "day8"
path = "day8.rs"
