[package]
name = "day15"
version = "0.1.0"
edition = "2021"

[dependencies]
aoc = { path = "../../aoc" }
intcode = { path = "../intcode-rs" }
rustc-hash = "*"

[[bin]]
name = "day15"
path = "day15.rs"
