[package]
name = "day7"
version = "0.1.0"
edition = "2021"

[dependencies]
aoc = { path = "../../aoc" }
intcode = { path = "../intcode-rs" }
itertools = "0.14.0"

[[bin]]
name = "day7"
path = "day7.rs"
