name: CI
on:
  pull_request:
  push:
    branches: ["main"]

defaults:
  run:
    shell: bash

jobs:

  # Check coding style
  rustfmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          for manifest in `find . -maxdepth 3 ! -path '*/day*' -name Cargo.toml`
          do
              echo check fmt for $manifest
              cargo fmt --all --manifest-path $manifest -- --check
          done

  # Check static analysis defaults
  clippy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          for manifest in `find . -maxdepth 3 ! -path '*/day*' -name Cargo.toml`
          do
              echo check clippy for $manifest
              cargo clippy --manifest-path $manifest -- --no-deps -D clippy::all -A clippy::pedantic -A clippy::nursery
          done

  # Check non-regression tests
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          for manifest in `find . -maxdepth 3 ! -path '*/day*' -name Cargo.toml`
          do
              echo test for $manifest
              cargo test --manifest-path $manifest -- --test-threads 4
          done
