name: CI
on:
  pull_request:
  push:
    branches: ["main"]

defaults:
  run:
    shell: bash

jobs:

  # Check coding style
  rustfmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          for manifest in `find . ! -path '*/day*' -name Cargo.toml`
          do
            echo check fmt for $manifest
            cargo fmt --all --manifest-path $manifest -- --check
          done

  # Check static analysis defaults
  clippy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          for manifest in `find . ! -path '*/day*' -name Cargo.toml`
          do
            echo check clippy for $manifest
            cargo clippy --manifest-path $manifest -- --no-deps -A clippy::all
          done

  # Check non-regression tests
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          for manifest in `find . ! -path '*/day*' -name Cargo.toml`
          do
            echo test for $manifest
            cargo test --manifest-path $manifest --
          done
