[package]
name = "day10"
version = "0.1.0"
edition = "2021"

[dependencies]
aoc = { path = "../../aoc" }
geo = "*"
geo-types = "*"
itertools = "*"
rustc-hash = "*"

[[bin]]
name = "day10"
path = "day10.rs"
