[package]
name = "day10"
version = "0.1.0"
edition = "2021"

[dependencies]
aoc = { path = "../../aoc" }
geo = "0.27.0"
geo-types = "0.7.12"
itertools = "0.12.0"

[[bin]]
name = "day10"
path = "day10.rs"
